### ISSUE TITLE
Could not find a version of package simpleid/simpleid-tool matching your minimum-stability (stable).

### ISSUE THREAD

**Issue by ubuntupunk** [simpleid/simpleid-tool#2]
Could not find a version of package simpleid/simpleid-tool matching your minimum-stability (stable).

**Comment by kelvinmo** [comment]
simpleid/simpleid-tool is still in development.  In order to download the package using composer, you need to specify the package with `simpleid/simpleid-tool:dev-master`.

See the [Composer manual page](https://getcomposer.org/doc/03-cli.md#require) for further details.
